In [ ]:
import numpy
print(numpy.__version__)


2.0.2


In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
#Create a numpy array from a Python list
l=[1,2,3,4,5,6,7,8,9]
a=np.array(l)#convert list ti n-dimensional array
print("Array from List",a)

Array from List [1 2 3 4 5 6 7 8 9]


In [ ]:
#Creating 1Darray
a=np.array([10,20,30,40])
print("1D array",a)

1D array [10 20 30 40]


In [ ]:
#create a 2D array
a=np.array([[10,20,30], [40,50,60]])
print("2D array",a)

2D array [[10 20 30]
 [40 50 60]]


In [ ]:
#create evenly spaced integers with range
a=np.arange(0,10,2)
print("Range Array",a)

Range Array [0 2 4 6 8]


In [ ]:
#create evenly spaced floats using linspace
a=np.linspace(0,1,5)
print("Linspace Array",a)

Linspace Array [0.   0.25 0.5  0.75 1.  ]


In [ ]:
#create a 2*3 array of all zeros
a=np.zeros((2,3))
print("Zeros Array",a)

Zeros Array [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#create a 3*2 array of all ones
a=np.ones((3,2))
print("Ones Array",a)

Ones Array [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#create a 2*2 array filled with value 7
a=np.full((2,2),7)
print("Full Array \n",a)

Full Array 
 [[7 7]
 [7 7]]


In [ ]:
#create a 2Darray with 2 rows and 3 columns
a=np.array([[10,20,30], [40,50,60]])
print("2D Array \n",a)

2D Array 
 [[10 20 30]
 [40 50 60]]


In [ ]:
#Shape tuple of(rows,columns)
print("Shape of Array",a.shape)

Shape of Array (2, 3)


In [ ]:
#Number of Dimensions(axes). 1D,2D,3D
print("Dimension of Array",a.ndim)

Dimension of Array 2


In [ ]:
#dtype:data type of the elements (int32,float64)
print("Data Type of Array",a.dtype)

Data Type of Array int64


In [ ]:
#size:total number of elements in the array
print("Size of Array",a.size)

Size of Array 6


In [ ]:
#each row=a product ; each column=a month(Jan to Mar)
s=np.array([
    [100,200,300],#Product A
     [400,500,600],#Product B
      [500,600,700]#Product C
    ])
print("Sales Data \n",s)

Sales Data 
 [[100 200 300]
 [400 500 600]
 [500 600 700]]


In [ ]:
#Elemnt at row 0,column 1(Product A in Feb)
print("Sales of Product A in Feb",s[0,1])

Sales of Product A in Feb 200


In [ ]:
#entire first row(Product A)
print("Sales of Product A",s[0])

Sales of Product A [100 200 300]


In [ ]:
#last column (March for all Products)
print("Sales of March",s[:,-1])

Sales of March [300 600 700]


In [ ]:
#Subarray: First 2 rows and 2 columns
print("Subarray \n",s[:2,:2])

Subarray 
 [[100 200]
 [400 500]]


In [ ]:
#reverse the order of rows(Products C,B,A)
print("Reverse Rows \n",s[::-1])

Reverse Rows 
 [[500 600 700]
 [400 500 600]
 [100 200 300]]


In [ ]:
#Every other column(Jan and Mar)
print("Every Other Column \n",s[:,::2])

Every Other Column 
 [[100 300]
 [400 600]
 [500 700]]


In [ ]:
print(s[-1:-3:-1])

[[500 600 700]
 [400 500 600]]


In [ ]:
print(s[-1:-3])

[]


In [ ]:
print(s[-3:-3:-1])

[]


In [ ]:
print(s[-2:-3:-2])

[[400 500 600]]


In [ ]:
print(s[-1:-3:-3])

[[500 600 700]]


In [ ]:
#create a 3*4 array with values 1-12
t=np.arange(1,13).reshape(3,4)
print(t)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(t[:,0])

[1 5 9]


In [ ]:
#retrieve last 2 columns
print(t[:,-2:])

[[ 3  4]
 [ 7  8]
 [11 12]]


In [ ]:
#reverse the array
print("Reverse Rows \n",t[::-1])

Reverse Rows 
 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
#define two arrays with same shape
a1=np.array([10,20,30,40])
a2=np.array([1,2,3,4])

In [ ]:
#print basic arithmetic operations
print("Addition:",a1+a2)
print("Subtraction:",a1-a2)
print("Multiplication:",a1*a2)
print("Division:",a1/a2)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


In [ ]:
#Array and Scalar operation
print("Add 100 to a1:",a1+100)

Add 100 to a1: [110 120 130 140]


In [ ]:
#create a 2d array
m=np.array([[10,20,30],[40,50,60]])
print("Total Sum",np.sum(m))
print("Mean Value",np.mean(m))
print("Standard Deviation",np.std(m))
print("Sum by Column(axis=0)",np.sum(m,axis=0))#applies through column
print("Sum by Row(axis=1)",np.sum(m,axis=1))#applies through row
print("Mean by row",np.mean(m,axis=1))

Total Sum 210
Mean Value 35.0
Standard Deviation 17.07825127659933
Sum by Column(axis=0) [50 70 90]
Sum by Column(axis=1) [ 60 150]
Mean by row [20. 50.]


In [ ]:
#Masking and Filtering
s=np.array([60,75,80,85,90,45])
#Create a boolean marks for scores>=70
p=s>=70
print("Pass Mark:",p)
#filter values using marks
print("Passing Marks",s[p])
#combine conditions :select scores between 70 and 90
print("Between 70 and 90",s[(s>=70)&(s<=90)])

Pass Mark: [False  True  True  True  True False]
Passing Marks [75 80 85 90]
Between 70 and 90 [75 80 85 90]


In [ ]:
#use np.where to assign labels
l=np.where(s>=70,"Pass","Fail")
print("Labels:",l)

Labels: ['Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail']


In [ ]:
#create an array with nan values
d=np.array([6.0,np.nan,7.0,np.nan,5.0])
#detect nan positions
print("Nan Mask:",np.isnan(d))
#aggregate safely while ignoring nans
print("Mean ignoring nans",np.nanmean(d))
#Replace nans with 0
f=np.nan_to_num(d,nan=0.0)
print("Replaced nans with 0",f)

Nan Mask: [False  True False  True False]
Mean ignoring nans 6.0
Replaced nans with 0 [6. 0. 7. 0. 5.]


In [ ]:
#create a 1D array of 12 elemnts
a=np.arange(12)
print("Original array:",a)
r=a.reshape(3,4)
print("Reshaped array",r)
ra=r.ravel()
f=r.flatten()
print("Raveled (1Dview):",ra)
print("Flattened (1D copy):",f)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Raveled (1Dview): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Flattened (1D copy): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print("Transpose array: \n",r.T)
#convert one row into a column
m=r[0]
m_c=m.reshape(-1,1)
print("Column Vector: \n",m_c)
#convert back to row
m_r=m_c.reshape(1,-1)
print("Row Vector: \n",m_r)

Transpose array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Column Vector: 
 [[0]
 [1]
 [2]
 [3]]
Row Vector: 
 [[0 1 2 3]]


In [ ]:
#combining arrays
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
#horizontal stack among columns
h=np.hstack((a,b))
print("Horizontal Stack: \n",h)
#vertical stack among rows
v=np.vstack((a,b))
print("Vertical Stack: \n",v)
#generic concatenate: axis=0 (rows), axis=1(columns)
c=np.concatenate((a,b),axis=0)
print("Concatenate Rows: \n",c)
c=np.concatenate((a,b),axis=1)
print("Concatenate Columns: \n",c)

Horizontal Stack: 
 [[1 2 5 6]
 [3 4 7 8]]
Vertical Stack: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate Rows: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate Columns: 
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#create a 2Darray
a=np.arange(16).reshape(4,4)
print("Original array: \n",a)
#split vertically into two 2*4 arrays
sv=np.vsplit(a,2)
print("Vertical Split(2*4 each)")
for s in sv:
  print(s)
#split horizontally into two 2*4 arrays
sr=np.hsplit(a,2)
print("Horizontal Split(2*4 each)")
for s in sr:
  print(s)

Original array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Vertical Split(2*4 each)
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
Horizontal Split(2*4 each)
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
#advanced indexing
a=np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
#select rows 0,2 and 3
s=a[:,[2,0,1]]
print("Selected Rows 0,2,3:\n",s)
#reorder columns
r=a[:,[2,0,1]]
print("Reordered Columns:\n",r)

Selected Rows 0,2,3:
 [[ 30  10  20]
 [ 60  40  50]
 [ 90  70  80]
 [120 100 110]]
Reordered Columns:
 [[ 30  10  20]
 [ 60  40  50]
 [ 90  70  80]
 [120 100 110]]


In [ ]:
d=np.array([45,512,89,33])
print("Original Array:",d)
#sorted values
print("Sorted Values:",np.sort(d))
print("Sorted Indices:",np.argsort(d))
print("Data sorted using indices:",d[np.argsort(d)])

Original Array: [45 12 89 33]
Sorted Values: [12 33 45 89]
Sorted Indices: [1 3 0 2]
Data sorted using indices: [12 33 45 89]


In [ ]:
#derived insights and data processing workflows
#simulated sales data (rows=products colums=months)
import numpy as np
s=np.array([
    [200,220,250,300],#product a
     [150,160,170,190],#product b
      [300,330,360,390]#product c
    ])
#Row wise sum
rs=np.sum(s,axis=1)
print("Total Sales per Product: \n",rs)
#Column mean
cm=np.mean(s,axis=0)
print("Average Monthly Sales: \n",cm)
#percent change across months
#(current-previous)/previous
pc=(s[:,1:]-s[:,:-1])/s[:,:-1]
print("Percentage change \n",pc)
print("Full mat \n",s)
print("Part mat \n",s[:,1:])
print("Part mat2 \n",s[:,:-1])

Total Sales per Product: 
 [ 970  670 1380]
Average Monthly Sales: 
 [216.66666667 236.66666667 260.         293.33333333]
Percentage change 
 [[0.1        0.13636364 0.2       ]
 [0.06666667 0.0625     0.11764706]
 [0.1        0.09090909 0.08333333]]
Full mat 
 [[200 220 250 300]
 [150 160 170 190]
 [300 330 360 390]]
Part mat 
 [[220 250 300]
 [160 170 190]
 [330 360 390]]
Part mat2 
 [[200 220 250]
 [150 160 170]
 [300 330 360]]


In [ ]:
#set seed for reproductibility
np.random.seed(3)
#Random Integers
r_ints=np.random.randint(1,100,size=(3,4))
print("Random Integers: \n",r_ints)
#Normally distributed values(mean=0,std=1)
ns=np.random.normal(loc=0,scale=1,size=5)
print("Normal Samples:",ns)
#random choices from list
o=['a','b','c']
c=np.random.choice(o,size=5,replace=True)
print("Random Choices:",c)


Random Integers: 
 [[25  4 57 73]
 [ 1 22 20 75]
 [42 11 22 39]]
Normal Samples: [-0.46004212 -0.05792084  2.07757414 -0.60131248  0.93923639]
Random Choices: ['c' 'a' 'b' 'c' 'b']
